# Generated by Django 3.0.2 on 2020-02-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0003_auto_20200227_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wsapp.Category', verbose_name='Категория'),
        ),
    ]
