# Generated by Django 3.0.2 on 2020-02-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0004_auto_20200227_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(related_name='vendors', to='wsapp.Category', verbose_name='Категория'),
        ),
    ]
