# Generated by Django 3.0.2 on 2020-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0005_auto_20200227_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ManyToManyField(related_name='categories', to='wsapp.Vendor', verbose_name='Производитель'),
        ),
    ]
