# Generated by Django 3.0.2 on 2020-02-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsapp', '0007_auto_20200227_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ManyToManyField(related_name='categories', to='wsapp.Vendor', verbose_name='Производитель'),
        ),
    ]
